### ISSUE TITLE
Exception in thread Thread-1 (_run_pareto_accumulation)

### ISSUE THREAD

**Issue by gmseabra** [recursionpharma/gflownet#134]
Hi guys,

First, thank you for making this resource available, the GFlowNet seems a really promising method.

My question is that I've installed locally it following the instructions on the README, and now I'm trying the example in  sEH fragment-based MOO task in `/gflownet/src/gflownet/tasks/seh_frag_moo.py`. However, the calculation always dies with the error message below. I've also tried the `seh_frag.py`, but it dies with the same message.

```
$ python seh_frag_moo.py
[...]
18/06/2024 18:13:28 - INFO - logger - Final generation steps completed - sampled_reward_avg:0.39 igd:0.42 lifetime_igd_frontOnly:0.43 PCent:1.87 lifetime_PCent_frontOnly:0.69
Exception in thread Thread-1 (_run_pareto_accumulation):
Traceback (most recent call last):
  File "/blue/lic/seabra/.conda/envs/gflownet/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/blue/lic/seabra/.conda/envs/gflownet/lib/python3.10/threading.py", line 953, in run
```

Here is my configuration:
```
$ python
Python 3.10.13 | packaged by conda-forge | (main, Dec 23 2023, 15:36:39) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> import torch_geometric as gn
>>> torch.__version__
'2.1.2+cu121'
>>> torch.version.cuda
'12.1'
>>> torch.cuda.get_device_name()
'NVIDIA A100-SXM4-80GB'
>>> torch.cuda.get_device_properties(0)
_CudaDeviceProperties(name='NVIDIA A100-SXM4-80GB', major=8, minor=0, total_memory=81050MB, multi_processor_count=108)
>>> gn.__version__
'2.4.0'
```

Am I missing something here? Thanks a lot!

**Comment by hdieckhaus** [comment]
@bengioe I have also encountered the same issue with a fresh install. have you had a chance to look into this? Thanks!
